export interface Destino {
  id: string;
  slug: string;
  nombre: string;
  zona: string;
  tipo: string;
  icon: string;
  descripcion: string;
  duracion_hrs: number;
  precio_entrada: string;
  dificultad: string;
  ideal_para: string[];
  horario: string;
  dias_abierto: string;
  mejor_hora: string;
  temporada_ideal: string;
  advertencias: string;
  como_llegar: string;
  que_llevar: string[];
  datos_curiosos: string[];
  errores_comunes: string[];
  lat: number;
  lng: number;
  imagen_hero: string;
  imagen_galeria: string[];
  seo?: {
    metaTitle: string;
    metaDescription: string;
    keywords: string[];
    faqPrincipales: { pregunta: string; respuesta: string }[];
  };
}

export const DESTINOS_DB: Destino[] = [
  // ─── DESTINOS ORIGINALES (8) ───────────────────────────────────────────────
  {
    id: "xilitla_pozas", slug: "las-pozas-jardin-surrealista",
    nombre: "Las Pozas (Jardín Surrealista)", zona: "Xilitla", tipo: "Arte & Naturaleza", icon: "Landmark",
    descripcion: "El icónico jardín surrealista de Edward James: esculturas de concreto entre cascadas y selva tropical.",
    duracion_hrs: 4, precio_entrada: "$180 MXN", dificultad: "media",
    ideal_para: ["fotografia", "pareja", "solo", "cultura"],
    horario: "09:00–18:00", dias_abierto: "Miércoles a Lunes (cerrado martes)",
    mejor_hora: "09:00–11:00", temporada_ideal: "Nov–Mar",
    advertencias: "Comprar ticket digital antes. Cerrado martes.",
    como_llegar: "1h 45min desde Valles · Taxi $1,200 · Bus $110",
    que_llevar: ["calzado antiderrapante", "repelente biodegradable"],
    datos_curiosos: ["Fue plantación de orquídeas", "Edward James nunca vivió en las estructuras"],
    errores_comunes: ["Llegar sin reservación", "Calzado liso"],
    lat: 21.3972, lng: -98.9939,
    imagen_hero: "/imagenes/las-pozas-jardin-surrealista/hero.webp",
    imagen_galeria: [
      "/imagenes/las-pozas-jardin-surrealista/gallery-1.jpg",
      "/imagenes/las-pozas-jardin-surrealista/gallery-2.jpg",
    ],
  },
  {
    id: "cascada_tamul", slug: "cascada-de-tamul",
    nombre: "Cascada de Tamul", zona: "Aquismón", tipo: "Aventura", icon: "Waves",
    descripcion: "La cascada más alta de SLP (105m), accesible remando por el río Tampaón. Espectacular caída turquesa.",
    duracion_hrs: 5, precio_entrada: "$220 MXN + $300 panga p/p", dificultad: "alta",
    ideal_para: ["aventura", "fotografia", "amigos"],
    horario: "08:00–17:00", dias_abierto: "Lun-Dom",
    mejor_hora: "08:00", temporada_ideal: "Ene–Abr",
    advertencias: "Lancheros dejan de salir a las 2 PM. SOLO EFECTIVO.",
    como_llegar: "45 min desde Valles → Tanchachín + lancha",
    que_llevar: ["chaleco salvavidas", "aqua shoes", "agua 2L"],
    datos_curiosos: ["105m de caída", "En octubre: agua turquesa + follaje naranja"],
    errores_comunes: ["Llegar tarde", "No llevar efectivo"],
    lat: 21.8014, lng: -99.1794,
    imagen_hero: "/imagenes/cascada-de-tamul/hero.jpg",
    imagen_galeria: [
      "/imagenes/cascada-de-tamul/gallery-1.jpg",
      "/imagenes/cascada-de-tamul/gallery-2.webp",
    ],
  },
  {
    id: "sotano_golondrinas", slug: "sotano-de-las-golondrinas",
    nombre: "Sótano de las Golondrinas", zona: "Aquismón", tipo: "Extrema", icon: "Bird",
    descripcion: "Abismo kárstico de 333m. Santuario de vencejos con vuelo espiral al amanecer.",
    duracion_hrs: 3, precio_entrada: "$100 MXN", dificultad: "media",
    ideal_para: ["fotografia", "naturaleza", "solo"],
    horario: "06:00–18:00", dias_abierto: "Lunes a Domingo",
    mejor_hora: "05:45 AM", temporada_ideal: "Nov–Mar",
    advertencias: "568 escalones para bajar; subida AGOTADORA.",
    como_llegar: "1h 15min desde Valles por sierra",
    que_llevar: ["chamarra", "lámpara", "calzado tenis"],
    datos_curiosos: ["Las aves son VENCEJOS, no golondrinas", "Fondo = 3 campos de fútbol"],
    errores_comunes: ["Llegar a las 9 AM cuando aves ya salieron"],
    lat: 21.6001, lng: -99.0989,
    imagen_hero: "/imagenes/sotano-de-las-golondrinas/hero.jpg",
    imagen_galeria: [
      "/imagenes/sotano-de-las-golondrinas/gallery-1.avif",
      "/imagenes/sotano-de-las-golondrinas/gallery-2.avif",
    ],
  },
  {
    id: "cascada_micos", slug: "cascadas-de-micos",
    nombre: "Cascadas de Micos", zona: "Ciudad Valles", tipo: "Aventura", icon: "Droplets",
    descripcion: "Serie de 7 cascadas con circuito de saltos, tirolesa, kayak y skybike.",
    duracion_hrs: 4, precio_entrada: "$100 MXN", dificultad: "media",
    ideal_para: ["amigos", "aventura"],
    horario: "08:00–18:00", dias_abierto: "Lunes a Domingo",
    mejor_hora: "09:00 AM", temporada_ideal: "Todo el año",
    advertencias: "Chaleco y casco OBLIGATORIO.",
    como_llegar: "20 min desde Valles · Combis $35 MXN c/30 min",
    que_llevar: ["aqua shoes", "ropa dry-fit"],
    datos_curiosos: ["El río más versátil de la zona"],
    errores_comunes: ["No ajustar bien el chaleco"],
    lat: 21.9958, lng: -99.1678,
    imagen_hero: "/imagenes/cascadas-de-micos/hero.jpg",
    imagen_galeria: [
      "/imagenes/cascadas-de-micos/gallery-1.webp",
      "/imagenes/cascadas-de-micos/gallery-2.jpg",
    ],
  },
  {
    id: "cascada_puente_dios", slug: "puente-de-dios-tamasopo",
    nombre: "Puente de Dios (Tamasopo)", zona: "Tamasopo", tipo: "Naturaleza", icon: "MountainSnow",
    descripcion: "Poza azul cobalto bajo puente natural. La luz entra a la cueva entre 11:00–13:00.",
    duracion_hrs: 3.5, precio_entrada: "$150 MXN", dificultad: "media",
    ideal_para: ["pareja", "fotografia"],
    horario: "08:00–17:00", dias_abierto: "Lunes a Domingo",
    mejor_hora: "11:00–13:00", temporada_ideal: "Ene–May",
    advertencias: "Corrientes fuertes; seguir cuerda de seguridad.",
    como_llegar: "1h desde Valles por autopista a SLP",
    que_llevar: ["aqua shoes OBLIGATORIOS", "chaleco"],
    datos_curiosos: ["Efecto de luz en la cueva único en México"],
    errores_comunes: ["No usar aqua shoes (piedras MUY resbalosas)"],
    lat: 21.9214, lng: -99.4217,
    imagen_hero: "/imagenes/puente-de-dios-tamasopo/hero.jpg",
    imagen_galeria: [
      "/imagenes/puente-de-dios-tamasopo/gallery-1.jpg",
      "/imagenes/puente-de-dios-tamasopo/gallery-2.jpg",
    ],
  },
  {
    id: "tamtoc", slug: "zona-arqueologica-tamtoc",
    nombre: "Zona Arqueológica Tamtoc", zona: "Tamuín", tipo: "Arqueología", icon: "BookOpen",
    descripcion: "El asentamiento prehispánico más importante de la cultura Huasteca.",
    duracion_hrs: 3, precio_entrada: "$95 MXN", dificultad: "baja",
    ideal_para: ["historia", "cultura", "familia"],
    horario: "09:00–17:00", dias_abierto: "Martes a Domingo",
    mejor_hora: "09:00 AM", temporada_ideal: "Dic–Feb",
    advertencias: "POCA sombra. Puede superar 45°C en mayo.",
    como_llegar: "45 min desde Valles",
    que_llevar: ["sombrero", "agua abundante", "protector solar"],
    datos_curiosos: ["Monumento 32 pesa 30 toneladas"],
    errores_comunes: ["No llevar agua", "Ir sin guía"],
    lat: 22.2131, lng: -98.8158,
    imagen_hero: "/imagenes/zona-arqueologica-tamtoc/hero.jpg",
    imagen_galeria: [
      "/imagenes/zona-arqueologica-tamtoc/gallery-1.jpg",
      "/imagenes/zona-arqueologica-tamtoc/gallery-2.jpg",
    ],
  },
  {
    id: "cascada_tamasopo", slug: "cascadas-de-tamasopo",
    nombre: "Cascadas de Tamasopo", zona: "Tamasopo", tipo: "Naturaleza", icon: "Droplet",
    descripcion: "Paraíso de agua azul turquesa con pozas para nadar, ideal para familias.",
    duracion_hrs: 4, precio_entrada: "$60 MXN", dificultad: "baja",
    ideal_para: ["familia", "relajacion", "fotografia"],
    horario: "08:00–17:00", dias_abierto: "Lunes a Domingo",
    mejor_hora: "10:00–14:00", temporada_ideal: "Nov–May",
    advertencias: "SOLO bloqueador biodegradable.",
    como_llegar: "45 min desde Valles por autopista",
    que_llevar: ["traje de baño", "bloqueador biodegradable"],
    datos_curiosos: ["Las pozas cambian de color según la estación"],
    errores_comunes: ["Usar bloqueador químico"],
    lat: 21.92, lng: -99.39,
    imagen_hero: "/imagenes/cascadas-de-tamasopo/hero.jpg",
    imagen_galeria: [
      "/imagenes/cascadas-de-tamasopo/gallery-1.jpg",
      "/imagenes/cascadas-de-tamasopo/gallery-2.webp",
    ],
  },
  {
    id: "balneario_taninul", slug: "balneario-taninul",
    nombre: "Balneario Taninul", zona: "Ciudad Valles", tipo: "Naturaleza", icon: "Thermometer",
    descripcion: "Aguas termales sulfurosas (36°C constante) y lodo terapéutico.",
    duracion_hrs: 4, precio_entrada: "$150 MXN", dificultad: "baja",
    ideal_para: ["familia", "pareja", "relajacion"],
    horario: "07:00–20:00", dias_abierto: "Lunes a Domingo",
    mejor_hora: "08:00 o 18:00", temporada_ideal: "Dic–Ene",
    advertencias: "NO llevar joyería de plata (azufre la oscurece).",
    como_llegar: "15 min desde Valles",
    que_llevar: ["traje de baño", "sandalias", "toalla"],
    datos_curiosos: ["Agua mantiene 36°C constante todo el año"],
    errores_comunes: ["Llevar joyería de plata"],
    lat: 21.9452, lng: -98.8895,
    imagen_hero: "/imagenes/balneario-taninul/hero.webp",
    imagen_galeria: [],
  },

  // ─── NUEVOS DESTINOS — TANDA 1 (8 sin Tambaque) ────────────────────────────

  {
    id: "cascadas-minas-viejas",
    slug: "cascadas-minas-viejas",
    nombre: "Cascadas de Minas Viejas",
    zona: "El Naranjo",
    tipo: "Aventura",
    icon: "Waves",
    descripcion: "Dos caídas gemelas de 50 m con pozas color turquesa rodeadas de selva preservada.",
    duracion_hrs: 4,
    precio_entrada: "$100 MXN",
    dificultad: "baja",
    ideal_para: ["natacion", "aventura", "familia", "fotografia"],
    horario: "08:00–18:00",
    dias_abierto: "Lunes a Domingo",
    mejor_hora: "08:00–10:00",
    temporada_ideal: "Oct–May",
    advertencias: "Respetar las zonas de nado señalizadas — hay corrientes fuertes en el canal central. El camino de acceso puede ser lodoso en temporada de lluvias. Solo efectivo.",
    como_llegar: "105 min desde Valles · Carretera 70 norte → desvío El Naranjo por Carr. 80",
    que_llevar: ["calzado acuático o tenis que puedan mojarse", "bloqueador solar biodegradable (obligatorio)", "cambio de ropa seca", "efectivo (sin cajero en la zona)", "repelente natural"],
    datos_curiosos: [
      "Consideradas de las cascadas con el agua más azul de toda la región por alta concentración de minerales kársticos.",
      "El nombre viene de una antigua explotación minera del siglo XIX en el ejido.",
    ],
    errores_comunes: ["Llegar sin efectivo", "Ir en temporada de lluvias sin verificar acceso"],
    lat: 22.576111,
    lng: -99.280556,
    imagen_hero: "/imagenes/cascadas-minas-viejas/hero.jpg",
    imagen_galeria: [
      "/imagenes/cascadas-minas-viejas/gallery-1.webp",
      "/imagenes/cascadas-minas-viejas/gallery-2.jpg",
    ],
    seo: {
      metaTitle: "Guía Cascadas Minas Viejas 2026 | El Naranjo SLP",
      metaDescription: "Descubre las Cascadas de Minas Viejas en 2026: precios, horarios, cómo llegar y consejos para ver el turquesa más intenso de la Huasteca Potosina. ¡Planea ya!",
      keywords: ["minas viejas cascadas", "el naranjo san luis potosi", "cascadas huasteca potosina", "minas viejas 2026", "pozas turquesa slp"],
      faqPrincipales: [
        { pregunta: "¿Cuánto cuesta la entrada a Minas Viejas en 2026?", respuesta: "El costo aproximado es de $100 MXN por persona. Solo efectivo, no hay cajero en la zona." },
        { pregunta: "¿Se puede nadar en las Cascadas de Minas Viejas?", respuesta: "Sí, hay pozas designadas con aguas tranquilas para nadar. Usa bloqueador biodegradable obligatoriamente." },
        { pregunta: "¿Cómo llegar a Minas Viejas desde Ciudad Valles?", respuesta: "Toma la carretera 70 norte y desvíate hacia El Naranjo por la 80. Son aproximadamente 95 km y 1 hora 45 minutos en auto." },
      ],
    },
  },

  {
    id: "laguna-media-luna",
    slug: "laguna-media-luna",
    nombre: "Manantial de la Media Luna",
    zona: "Rioverde",
    tipo: "Bienestar",
    icon: "Droplet",
    descripcion: "Manantial termal cristalino con visibilidad de 30 m y vestigios prehispánicos sumergidos.",
    duracion_hrs: 6,
    precio_entrada: "$150 MXN",
    dificultad: "baja",
    ideal_para: ["buceo", "snorkel", "fotografia", "pareja"],
    horario: "08:00–18:30",
    dias_abierto: "Lunes a Domingo",
    mejor_hora: "09:00–11:00",
    temporada_ideal: "Todo el año",
    advertencias: "No tocar el fondo para no levantar sedimentos. Chaleco salvavidas obligatorio para no-buceadores. Bloqueador no biodegradable estrictamente prohibido.",
    como_llegar: "120 min desde Valles · Carretera 70 poniente hasta Rioverde → señales al Ejido El Jabalí",
    que_llevar: ["equipo de snorkel (o rentar en sitio)", "traje de baño", "toalla", "googles de natación", "efectivo"],
    datos_curiosos: [
      "Se han encontrado ofrendas prehispánicas y posibles restos de mamut en el fondo del manantial.",
      "El nombre 'Media Luna' viene de la forma semicircular perfecta del espejo de agua.",
    ],
    errores_comunes: ["No reservar en temporada alta (cupo limitado)", "Llevar bloqueador químico"],
    lat: 21.859722,
    lng: -100.012500,
    imagen_hero: "/imagenes/laguna-media-luna/hero.jpg",
    imagen_galeria: [
      "/imagenes/laguna-media-luna/gallery-1.avif",
      "/imagenes/laguna-media-luna/gallery-2.webp",
    ],
    seo: {
      metaTitle: "Laguna Media Luna Rioverde 2026 | Guía de Viaje",
      metaDescription: "Visita el Manantial de la Media Luna en 2026: buceo, snorkel y aguas termales a 27°C en San Luis Potosí. Precios, reservaciones y cómo llegar desde Ciudad Valles.",
      keywords: ["laguna media luna rioverde", "manantial san luis potosi", "buceo media luna", "que hacer en rioverde", "media luna 2026"],
      faqPrincipales: [
        { pregunta: "¿Qué temperatura tiene el agua de la Media Luna?", respuesta: "El agua se mantiene constante entre 27°C y 29°C durante todo el año, independientemente de la temporada." },
        { pregunta: "¿Es necesario saber bucear para disfrutar la Media Luna?", respuesta: "No, puedes practicar snorkel o nadar con googles y ver el fondo cristalino desde la superficie." },
        { pregunta: "¿Hay límite de personas en la Media Luna?", respuesta: "Sí, el acceso está controlado para preservar el ecosistema. Se recomienda reservar en temporada alta." },
      ],
    },
  },

  {
    id: "cascada-el-aguacate",
    slug: "cascada-el-aguacate",
    nombre: "Cascada El Aguacate",
    zona: "Aquismón",
    tipo: "Aventura",
    icon: "Leaf",
    descripcion: "Caída de 70 m entre cañones de selva densa — uno de los secretos mejor guardados de Aquismón.",
    duracion_hrs: 3,
    precio_entrada: "$50 MXN",
    dificultad: "media",
    ideal_para: ["senderismo", "fotografia", "naturaleza", "aventura"],
    horario: "09:00–17:00",
    dias_abierto: "Lunes a Domingo",
    mejor_hora: "15:00–16:30",
    temporada_ideal: "Dic–Abr",
    advertencias: "Senderos resbaladizos — especialmente en el descenso hacia la poza. Sin señal de celular en toda la ruta. Guía local obligatorio. Coordenadas aproximadas — verificar GPS antes de ir.",
    como_llegar: "70 min desde Valles · Carretera 85 sur → desvío al Ejido El Aguacate antes de Aquismón",
    que_llevar: ["calzado de montaña con suela de agarre (obligatorio)", "bastones de trekking (recomendado)", "agua suficiente para 4 horas", "repelente natural", "bloqueador biodegradable"],
    datos_curiosos: [
      "Es una de las cascadas más altas y menos documentadas de la zona de Aquismón.",
      "Los guías locales la llaman 'la cascada que los turistas aún no descubrieron'.",
    ],
    errores_comunes: ["No contratar guía local", "Ir con calzado inadecuado"],
    lat: 21.668240,
    lng: -99.081560,
    imagen_hero: "/imagenes/cascada-el-aguacate/hero.jpg",
    imagen_galeria: [
      "/imagenes/cascada-el-aguacate/gallery-1.webp",
      "/imagenes/cascada-el-aguacate/gallery-2.jpg",
    ],
    seo: {
      metaTitle: "Cascada El Aguacate Aquismón 2026 | Guía Huasteca",
      metaDescription: "Cascada El Aguacate en Aquismón: 70 metros de caída, sendero de selva y pozas naturales. Guía 2026 con precios, cómo llegar y lo que nadie te cuenta. ¡Descúbrela!",
      keywords: ["cascada el aguacate aquismón", "cascadas secretas huasteca potosina", "senderismo aquismón", "cascadas slp 2026", "turismo aventura san luis potosi"],
      faqPrincipales: [
        { pregunta: "¿Es difícil llegar a la Cascada El Aguacate?", respuesta: "La caminata es de dificultad media — unos 45 minutos por sendero de selva. Se requiere calzado de montaña y guía local obligatorio." },
        { pregunta: "¿Hay baños en la Cascada El Aguacate?", respuesta: "Las instalaciones son mínimas. Hay baños básicos en la comunidad ejidal a la entrada." },
        { pregunta: "¿Es apto para niños la Cascada El Aguacate?", respuesta: "Se recomienda para niños mayores de 10 años con experiencia en caminata. El terreno es irregular y hay tramos empinados." },
      ],
    },
  },

  {
    id: "cascada-el-salto",
    slug: "cascada-el-salto",
    nombre: "Cascada El Salto",
    zona: "El Naranjo",
    tipo: "Naturaleza",
    icon: "Droplet",
    descripcion: "Pared de roca kárstica de 70 m con pozas turquesas permanentes — con o sin cascada es espectacular.",
    duracion_hrs: 3,
    precio_entrada: "$50 MXN",
    dificultad: "baja",
    ideal_para: ["natacion", "fotografia", "familia"],
    horario: "08:00–17:30",
    dias_abierto: "Lunes a Domingo",
    mejor_hora: "Mañana temprana",
    temporada_ideal: "Sep–Oct (cascada activa) · pozas todo el año",
    advertencias: "Piso extremadamente resbaladizo en las pozas — accidentes frecuentes sin calzado adecuado. La cascada principal puede estar completamente seca la mayor parte del año.",
    como_llegar: "110 min desde Valles · Desde El Naranjo, carretera hacia Ciudad del Maíz · 8 km pavimentado",
    que_llevar: ["calzado acuático — piso muy resbaladizo", "ropa ligera y traje de baño", "protección solar", "comida (sin restaurantes en el sitio)", "efectivo"],
    datos_curiosos: [
      "El flujo se desvía artificialmente hacia una planta hidroeléctrica — por eso la cascada 'desaparece' en temporada seca.",
      "En septiembre de 2024, las lluvias excepcionales la activaron por 3 semanas continuas.",
    ],
    errores_comunes: ["Ir esperando ver la cascada sin verificar antes", "No llevar calzado antiderrapante"],
    lat: 22.592500,
    lng: -99.308333,
    imagen_hero: "/imagenes/cascada-el-salto/hero.jpg",
    imagen_galeria: [
      "/imagenes/cascada-el-salto/gallery-1.jpg",
      "/imagenes/cascada-el-salto/gallery-2.jpg",
    ],
    seo: {
      metaTitle: "Cascada El Salto El Naranjo 2026 | Guía Completa",
      metaDescription: "Todo sobre Cascada El Salto en El Naranjo, SLP: cuándo cae de verdad, precios 2026, pozas turquesas y cómo combinarla con El Meco en un solo día. ¡Entra!",
      keywords: ["cascada el salto el naranjo", "pozas azules el naranjo slp", "cascadas huasteca potosina 2026", "turismo el naranjo san luis potosi", "cascada el salto slp"],
      faqPrincipales: [
        { pregunta: "¿Por qué no tiene agua la Cascada El Salto?", respuesta: "El flujo se desvía a una planta hidroeléctrica. Solo cae con lluvias excepcionales, principalmente en septiembre y octubre." },
        { pregunta: "¿Se puede nadar si la cascada El Salto no tiene agua?", respuesta: "Sí, las pozas naturales mantienen agua turquesa cristalina todo el año, con o sin la caída activa." },
        { pregunta: "¿Hay restaurantes cerca de Cascada El Salto?", respuesta: "No en el sitio, pero en El Naranjo (a 8 km) hay varios restaurantes con comida típica huasteca." },
      ],
    },
  },

  {
    id: "cascada-el-meco",
    slug: "cascada-el-meco",
    nombre: "Cascada El Meco",
    zona: "El Naranjo",
    tipo: "Aventura",
    icon: "Bird",
    descripcion: "Cascada constante de 35 m sobre roca caliza — la única de El Naranjo que cae todo el año.",
    duracion_hrs: 2,
    precio_entrada: "$60 MXN",
    dificultad: "baja",
    ideal_para: ["fotografia", "familia", "pareja"],
    horario: "08:00–18:00",
    dias_abierto: "Lunes a Domingo",
    mejor_hora: "17:00–18:00",
    temporada_ideal: "Nov–May",
    advertencias: "Corrientes fuertes en el centro del río — no nadar fuera de las zonas permitidas. La panga no opera si el río está crecido.",
    como_llegar: "105 min desde Valles · Desde El Naranjo, 5 km señalizados hasta el embarcadero",
    que_llevar: ["cámara o teléfono con funda impermeable", "repelente natural", "ropa cómoda", "efectivo para panga y restaurantes"],
    datos_curiosos: [
      "Su nombre proviene de los monos 'mecos' (monos araña) que habitaban la zona antes de la deforestación del siglo XX.",
      "Es la única cascada permanente del municipio de El Naranjo — cae todo el año sin importar la temporada.",
    ],
    errores_comunes: ["Ir sin efectivo para la panga (~$150 MXN)", "No preguntar si la panga opera ese día"],
    lat: 22.585556,
    lng: -99.300556,
    imagen_hero: "/imagenes/cascada-el-meco/hero.avif",
    imagen_galeria: [
      "/imagenes/cascada-el-meco/gallery-1.jpg",
      "/imagenes/cascada-el-meco/gallery-2.jpg",
    ],
    seo: {
      metaTitle: "Cascada El Meco El Naranjo 2026 | Mirador y Pangas",
      metaDescription: "Cascada El Meco en El Naranjo: la única cascada permanente de la zona. Guía 2026 con precios de panga, rappel, restaurantes con vista y cómo llegar. ¡Descúbrela!",
      keywords: ["cascada el meco el naranjo", "paseo en panga huasteca", "el meco san luis potosi 2026", "cascadas permanentes huasteca", "que hacer en el naranjo slp"],
      faqPrincipales: [
        { pregunta: "¿El mirador de Cascada El Meco es gratuito?", respuesta: "Sí, el mirador desde la carretera es completamente gratuito. El acceso al río y las pangas tienen costo adicional (~$60 MXN entrada, ~$150 MXN panga)." },
        { pregunta: "¿Se puede hacer rappel en Cascada El Meco?", respuesta: "Sí, hay operadores locales certificados que ofrecen rappel en la cascada. Consulta directamente en el sitio." },
        { pregunta: "¿Hay restaurantes con vista a Cascada El Meco?", respuesta: "Sí, varios restaurantes tienen terrazas sobre el río con vista directa a la cascada — una de las mejores experiencias de El Naranjo." },
      ],
    },
  },

  {
    id: "sotano-de-las-huahuas",
    slug: "sotano-de-las-huahuas",
    nombre: "Sótano de las Huahuas",
    zona: "Aquismón",
    tipo: "Extrema",
    icon: "MountainSnow",
    descripcion: "Abismo de 478 m donde miles de loros y vencejos dibujan espirales al amanecer y atardecer.",
    duracion_hrs: 3,
    precio_entrada: "$60 MXN",
    dificultad: "media",
    ideal_para: ["fotografia", "naturaleza", "aventura"],
    horario: "06:00–19:00",
    dias_abierto: "Lunes a Domingo",
    mejor_hora: "17:30–18:30",
    temporada_ideal: "Mar–Oct",
    advertencias: "Caminata de subida intensa — no apta para personas con problemas de rodillas. No acercarse al borde sin guía. Sin señal de celular en todo el trayecto.",
    como_llegar: "75 min desde Valles · Carretera 85 sur → desvío San Pedro de las Anonas · Terracería final",
    que_llevar: ["lámpara de mano o frontal", "calzado de montaña con agarre", "binoculares", "cámara con teleobjetivo", "agua y snacks", "ropa abrigadora para el amanecer"],
    datos_curiosos: [
      "Con 478 metros de profundidad, es uno de los abismos kársticos más profundos de México.",
      "Los lugareños llaman 'huahuas' a los loros verdes en lengua Tének — de ahí el nombre.",
    ],
    errores_comunes: ["Llegar tarde sin tiempo para ver el vuelo", "No llevar guía — el borde no tiene barandales"],
    lat: 21.603889,
    lng: -99.043889,
    imagen_hero: "/imagenes/sotano-de-las-huahuas/hero.jpg",
    imagen_galeria: [
      "/imagenes/sotano-de-las-huahuas/gallery-1.jpg",
    ],
    seo: {
      metaTitle: "Sótano de las Huahuas 2026 | Espectáculo de Aves",
      metaDescription: "Sótano de las Huahuas en Aquismón: 478 m de profundidad y miles de loros en espiral al atardecer. Guía 2026 con horarios, caminata y diferencias con las Golondrinas.",
      keywords: ["sótano de las huahuas aquismón", "abismo loros huasteca potosina", "senderismo aquismón slp", "huahuas 2026", "sotanos huasteca potosina"],
      faqPrincipales: [
        { pregunta: "¿A qué hora salen las aves del Sótano de las Huahuas?", respuesta: "Los loros salen al amanecer (6:00–7:00 AM) y regresan al atardecer (18:00–19:00 PM). El atardecer suele ser más espectacular por la luz." },
        { pregunta: "¿En qué se diferencia el Sótano de las Huahuas del Sótano de las Golondrinas?", respuesta: "Las Golondrinas (333 m) tiene vencejos y el vuelo icónico es al amanecer. Las Huahuas (478 m) alberga loros verdes y el mejor espectáculo es al atardecer. Son experiencias distintas." },
        { pregunta: "¿Es difícil la caminata al Sótano de las Huahuas?", respuesta: "La caminata de subida es de 30–40 minutos de intensidad media. Requiere calzado de montaña. No es apta para personas con problemas serios de movilidad." },
      ],
    },
  },

  {
    id: "cuevas-de-mantetzulel",
    slug: "cuevas-de-mantetzulel",
    nombre: "Cuevas de Mantetzulel",
    zona: "Aquismón",
    tipo: "Naturaleza",
    icon: "Sun",
    descripcion: "Cuatro cuevas sagradas con techos colapsados — la luz entra desde arriba como columnas sólidas.",
    duracion_hrs: 4,
    precio_entrada: "$70 MXN",
    dificultad: "media",
    ideal_para: ["fotografia", "cultura", "naturaleza"],
    horario: "09:00–17:00",
    dias_abierto: "Lunes a Domingo",
    mejor_hora: "11:00–13:00",
    temporada_ideal: "Oct–May",
    advertencias: "Senderos muy resbaladizos después de lluvia — posponer si hubo lluvia reciente. Sin señal de celular. Guía comunitario obligatorio. Coordenadas aproximadas — verificar GPS antes de ir.",
    como_llegar: "70 min desde Valles · Desde Aquismón, 12 km hacia comunidad Mantetzulel · Últimos 5 km terracería",
    que_llevar: ["calzado con suela antideslizante (obligatorio)", "linterna o frontal", "repelente natural", "ropa que no importe ensuciar", "agua para 4 horas"],
    datos_curiosos: [
      "Los habitantes Tének consideran estas cuevas como portales de curación — aún se realizan ceremonias tradicionales.",
      "La Cueva del Espíritu Santo no es un túnel: es una bóveda abierta al cielo con 30 metros de altura.",
    ],
    errores_comunes: ["Ir sin guía comunitario", "Visitar después de lluvia reciente (senderos peligrosos)"],
    lat: 21.631450,
    lng: -99.064820,
    imagen_hero: "/imagenes/cuevas-de-mantetzulel/hero.jpg",
    imagen_galeria: [
      "/imagenes/cuevas-de-mantetzulel/gallery-1.jpg",
      "/imagenes/cuevas-de-mantetzulel/gallery-2.jpg",
    ],
    seo: {
      metaTitle: "Cuevas de Mantetzulel Aquismón 2026 | Guía Completa",
      metaDescription: "Cuevas de Mantetzulel en Aquismón: bóvedas sagradas con luz cenital y turismo comunitario Tének. Guía 2026 con precios, caminata y el mejor horario para la foto perfecta.",
      keywords: ["cuevas mantetzulel aquismón", "espeleología huasteca potosina", "turismo comunitario tének slp", "mantetzulel 2026", "cuevas sagradas san luis potosi"],
      faqPrincipales: [
        { pregunta: "¿Cuántas cuevas se visitan en Mantetzulel?", respuesta: "El recorrido estándar visita 2 cuevas grandes. Con tiempo y condición física se pueden explorar las 4 cavidades del conjunto." },
        { pregunta: "¿Hay murciélagos en las Cuevas de Mantetzulel?", respuesta: "Sí, habitan en las zonas altas de las bóvedas, pero no representan riesgo para los visitantes con guía." },
        { pregunta: "¿Se necesita equipo especial para visitar Mantetzulel?", respuesta: "No equipo de espeleología avanzada. Solo calzado antideslizante, linterna y ropa que pueda ensuciarse." },
      ],
    },
  },

  {
    id: "nacimiento-huichihuayan",
    slug: "nacimiento-huichihuayan",
    nombre: "Nacimiento de Huichihuayán",
    zona: "Huehuetlán",
    tipo: "Naturaleza",
    icon: "Waves",
    descripcion: "Río cristalino que nace de una cueva — tan claro que se ven los peces en el fondo desde la orilla.",
    duracion_hrs: 3,
    precio_entrada: "$30 MXN",
    dificultad: "baja",
    ideal_para: ["natacion", "familia", "fotografia"],
    horario: "08:30–18:00",
    dias_abierto: "Lunes a Domingo",
    mejor_hora: "15:00–17:00",
    temporada_ideal: "Todo el año",
    advertencias: "Hay zonas profundas cerca del nacimiento — precaución con niños. Destino poco documentado — verificar condiciones antes de ir.",
    como_llegar: "80 min desde Valles · Carretera 85 sur hacia Tamazunchale · Desvío a Huehuetlán",
    que_llevar: ["traje de baño", "sandalias acuáticas", "alimentos (opciones limitadas en el sitio)", "googles de natación"],
    datos_curiosos: [
      "Huichihuayán es uno de los pueblos más activos en la preservación de la danza de los Voladores de Palo.",
      "El agua es tan cristalina que la comunidad local la usa directamente para consumo humano.",
    ],
    errores_comunes: ["No preguntar en el pueblo sobre la danza de Voladores", "No llevar googles para ver los peces"],
    lat: 21.483333,
    lng: -98.966667,
    imagen_hero: "/imagenes/nacimiento-huichihuayan/hero.jpg",
    imagen_galeria: [
      "/imagenes/nacimiento-huichihuayan/gallery-1.jpg",
      "/imagenes/nacimiento-huichihuayan/gallery-2.jpg",
    ],
    seo: {
      metaTitle: "Nacimiento de Huichihuayán 2026 | Huehuetlán SLP",
      metaDescription: "Nacimiento de Huichihuayán en Huehuetlán: río cristalino con peces visibles y la danza de los Voladores. El destino más auténtico del sur de la Huasteca. Guía 2026 completa.",
      keywords: ["nacimiento huichihuayán huehuetlán", "rio cristalino huasteca potosina", "voladores huichihuayan", "turismo huehuetlán slp 2026", "destinos sur huasteca potosina"],
      faqPrincipales: [
        { pregunta: "¿El agua de Huichihuayán está fría?", respuesta: "Es fresca y agradable, no tan fría como Tambaque. El clima cálido de la zona la mantiene a una temperatura ideal para nadar." },
        { pregunta: "¿Se puede rentar chaleco en Huichihuayán?", respuesta: "Sí, hay puestos locales que rentan chalecos y llantas a precios accesibles." },
        { pregunta: "¿Qué son los Voladores de Huichihuayán?", respuesta: "Es una danza ritual prehispánica declarada Patrimonio de la Humanidad por la UNESCO. En Huichihuayán se practica activamente — pregunta en el pueblo si hay presentación." },
      ],
    },
  },

  // ─── NUEVOS DESTINOS — TANDA 2 (4 del PDF) ─────────────────────────────────

  // nacimiento-tambaque — versión corregida con datos del PDF
  // Precio: $10 MXN · Coords exactas · Horario 09:00 · Estacionamiento $30 MXN extra
  {
    id: "nacimiento-tambaque",
    slug: "nacimiento-tambaque",
    nombre: "Nacimiento de Tambaque",
    zona: "Aquismón",
    tipo: "Naturaleza",
    icon: "Droplet",
    descripcion: "Oasis donde el río Coy brota de la Sierra de Tanchanaco en pozas de azul cristalino, con corriente casi nula.",
    duracion_hrs: 3,
    precio_entrada: "$10 MXN",
    dificultad: "baja",
    ideal_para: ["natacion", "familia", "relajacion"],
    horario: "09:00–18:00",
    dias_abierto: "Lunes a Domingo",
    mejor_hora: "09:00–11:00",
    temporada_ideal: "Oct–May",
    advertencias: "Temperatura del agua muy fría (nace de acuífero subterráneo) — choque térmico si entras rápido. Piso resbaladizo dentro del agua — calzado acuático obligatorio. Estacionamiento $30 MXN adicional.",
    como_llegar: "55 min desde Valles · Carretera 85 sur → Crucero San Pedro de las Anonas · 100% pavimentado",
    que_llevar: ["aquashoes o calzado acuático", "efectivo en denominaciones bajas (sin cajero ni terminal)", "comida propia (opciones solo fines de semana)", "protector solar biodegradable", "repelente natural"],
    datos_curiosos: [
      "En 1950 el nacimiento se secó completamente. El 10 de mayo de 1951, tras una gran tormenta, brotó con tal fuerza que llenó el balneario en una sola noche — los locales lo recuerdan como 'el milagro de Tambaque'.",
      "Tambaque significa 'lugar de agua bajita' en lengua Tének, referencia a la poca profundidad de sus pozas.",
    ],
    errores_comunes: ["No llevar calzado acuático (piso con algas muy resbaladizo)", "Entrar al agua rápido sin aclimatarse (choque térmico)"],
    lat: 21.687222,
    lng: -99.042778,
    imagen_hero: "/imagenes/nacimiento-tambaque/hero.webp",
    imagen_galeria: [
      "/imagenes/nacimiento-tambaque/gallery-1.webp",
      "/imagenes/nacimiento-tambaque/gallery-2.webp",
    ],
    seo: {
      metaTitle: "Balneario Tambaque Aquismón 2026 | Guía, Precios y Cómo Llegar",
      metaDescription: "Descubre el Nacimiento de Tambaque en Aquismón, SLP. Paraíso de aguas cristalinas ideal para familias. Precios 2026, ubicación exacta y mejores consejos de viaje.",
      keywords: ["balneario tambaque slp", "nacimiento de tambaque aquismón", "qué hacer en aquismón huasteca", "aguas cristalinas san luis potosí", "turismo aquismón 2026"],
      faqPrincipales: [
        { pregunta: "¿Qué significa Tambaque?", respuesta: "En lengua huasteca Tének significa 'lugar de agua bajita', referencia a la poca profundidad de sus pozas — ideal para niños y no nadadores." },
        { pregunta: "¿Pueden entrar niños pequeños a Tambaque?", respuesta: "Es el paraje más recomendado de la Huasteca para niños pequeños: corriente casi nula, agua playita y senderos seguros con andadores de piedra." },
        { pregunta: "¿Hay comida en Tambaque?", respuesta: "Los fines de semana y temporada alta hay venta de comida típica: enchiladas huastecas, boles y tamales. Entre semana se recomienda llevar alimentos propios." },
      ],
    },
  },

  {
    id: "voladores-tamaleton",
    slug: "voladores-tamaleton",
    nombre: "Voladores de Tamaletón",
    zona: "Tancanhuitz",
    tipo: "Arte & Cultura",
    icon: "Wind",
    descripcion: "El ritual prehispánico más antiguo de la Huasteca — 5 hombres vuelan desde un mástil de 30 m en honor al sol.",
    duracion_hrs: 4,
    precio_entrada: "$100 MXN",
    dificultad: "baja",
    ideal_para: ["cultura", "fotografia", "historia"],
    horario: "09:00–17:00",
    dias_abierto: "Jueves a Domingo (mayor actividad) · Lun-Mié menor actividad",
    mejor_hora: "11:30–13:30",
    temporada_ideal: "Dic–Feb",
    advertencias: "El vuelo se cancela con lluvia o viento — no garantizado para visitantes individuales sin grupo de 30+. Sin señal telefónica en la parte alta de Tamaletón. No conducir de noche hacia Tancanhuitz.",
    como_llegar: "52 min desde Valles · Carretera 85 sur → Crucero Aquismón → Tancanhuitz → Centro Ceremonial",
    que_llevar: ["efectivo (sin cajeros en Tamaletón)", "ropa cómoda para calor", "cámara fotográfica", "agua suficiente", "respeto y disposición para el silencio durante los rezos"],
    datos_curiosos: [
      "El ritual suma exactamente 52 vueltas (13 × 4 danzantes) — el número del 'Siglo Indígena' o ciclo del Fuego Nuevo mesoamericano.",
      "Bajudh (Jacinta) fue la primera mujer en convertirse en voladora oficial de Tamaletón, rompiendo siglos de prohibición.",
    ],
    errores_comunes: ["Llegar esperando vuelo garantizado sin grupo previo", "No llevar efectivo"],
    lat: 21.592222,
    lng: -98.964722,
    imagen_hero: "/imagenes/voladores-tamaleton/hero.jpg",
    imagen_galeria: [
      "/imagenes/voladores-tamaleton/gallery-1.jpg",
      "/imagenes/voladores-tamaleton/gallery-2.jpg",
    ],
    seo: {
      metaTitle: "Voladores de Tamaletón 2026 | Guía del Ritual Sagrado Teenek",
      metaDescription: "Descubre el Centro Ceremonial Tamaletón en Tancanhuitz. Guía de precios 2026, logística desde Ciudad Valles y el misterio de la Danza del Gavilán Tének. ¡Visítalo ahora!",
      keywords: ["voladores de tamaletón", "huasteca potosina turismo cultural 2026", "danza del gavilán tancanhuitz", "tancanhuitz san luis potosí", "cultura tének huasteca"],
      faqPrincipales: [
        { pregunta: "¿Los Voladores de Tamaletón son lo mismo que los de Papantla?", respuesta: "No. Aunque comparten el concepto del vuelo, Tamaletón pertenece a la etnia Tének, usa vestimenta de manta blanca con plumas naturales y tiene origen histórico independiente vinculado al gavilán sagrado, no al quetzal." },
        { pregunta: "¿Pueden volar mujeres en Tamaletón?", respuesta: "Sí. Tamaletón hizo historia con Bajudh (Jacinta), la primera mujer en romper la prohibición patriarcal y convertirse en voladora oficial." },
        { pregunta: "¿Está garantizado ver el vuelo si voy por mi cuenta?", respuesta: "No. El ritual se programa solo para grupos de 30+ personas o en fechas festivas. Los visitantes individuales pueden ver el mástil y el museo, pero no tienen garantizado presenciar el vuelo." },
      ],
    },
  },

  {
    id: "rio-tampaon-rafting",
    slug: "rio-tampaon-rafting",
    nombre: "Río Tampaón — Rafting Clase III",
    zona: "Aquismón",
    tipo: "Aventura",
    icon: "Anchor",
    descripcion: "14 km de rápidos Clase III en aguas turquesa por un cañón de 500 m — uno de los 10 ríos más escénicos de Norteamérica.",
    duracion_hrs: 7,
    precio_entrada: "$1,670 MXN (tour completo)",
    dificultad: "media",
    ideal_para: ["aventura", "amigos", "fotografia"],
    horario: "09:00–18:00",
    dias_abierto: "Lunes a Domingo (reservación requerida)",
    mejor_hora: "11:00–13:00",
    temporada_ideal: "Nov–Mar",
    advertencias: "Nunca navegar por cuenta propia en jul-ago — crecidas repentinas de varios metros en minutos. Guías NO pueden suministrar medicamentos — llevar los propios. Solo efectivo en Tanchachín.",
    como_llegar: "45 min desde Valles · Carretera 70 → desvío Ejido Tanchachín · Últimos 18 km terracería transitable",
    que_llevar: ["calcetines de algodón dentro del calzado acuático (evitan ampollas)", "doble muda de ropa seca en el vehículo", "bloqueador 100% biodegradable (obligatorio)", "GoPro con soporte de pecho o casco únicamente", "medicamentos propios"],
    datos_curiosos: [
      "El agua turquesa proviene de la alta concentración de minerales kársticos en el lecho — el mismo mecanismo que colorea las cascadas de Tamul.",
      "El rápido 'La Tumba' ocurre donde las paredes del cañón se cierran tanto que el eco desaparece — el silencio absoluto antes del rápido más técnico del descenso.",
    ],
    errores_comunes: ["Ir sin reservación en temporada alta", "Llevar bloqueador convencional (prohibido y multa)"],
    lat: 22.063222,
    lng: -99.010389,
    imagen_hero: "/imagenes/rio-tampaon-rafting/hero.jpg",
    imagen_galeria: [
      "/imagenes/rio-tampaon-rafting/gallery-1.jpg",
      "/imagenes/rio-tampaon-rafting/gallery-2.jpg",
    ],
    seo: {
      metaTitle: "Rafting Río Tampaón 2026 | Guía Experta Huasteca Potosina",
      metaDescription: "Vive el mejor rafting de México en el Río Tampaón. Precios 2026 ($1,450–$1,890 MXN), logística desde Ciudad Valles y consejos de seguridad. ¡Reserva tu aventura turquesa hoy!",
      keywords: ["rafting huasteca potosina 2026", "río tampaón rápidos clase III", "tours ciudad valles rafting", "precio rafting río tampaón", "mejor época rafting san luis potosí"],
      faqPrincipales: [
        { pregunta: "¿Es seguro hacer rafting en el Río Tampaón si no sé nadar?", respuesta: "Sí, siempre que uses el equipo de flotación de alta calidad de las operadoras certificadas. Debes informar al guía antes de subir para ubicarte estratégicamente en la balsa." },
        { pregunta: "¿Qué pasa si mi tour de rafting se cancela por el nivel del río?", respuesta: "La mayoría de operadoras ofrecen cambio de actividad a un río más tranquilo (como Micos) o reprogramación. Los reembolsos totales dependen de qué tan anticipado se confirme la inviabilidad del descenso." },
        { pregunta: "¿Puedo llevar mi cámara GoPro al rafting en el Tampaón?", respuesta: "Sí, con soporte de pecho o casco únicamente. Está prohibido llevarla en la mano — ambas manos deben estar libres para remar y sujetarse de las cuerdas de seguridad." },
      ],
    },
  },

  {
    id: "xilitla-pueblo-magico",
    slug: "xilitla-pueblo-magico",
    nombre: "Xilitla — Pueblo Mágico Surrealista",
    zona: "Xilitla",
    tipo: "Arte & Cultura",
    icon: "Landmark",
    descripcion: "Donde el concreto cobra vida y la selva se vuelve geométrica — Las Pozas de Edward James y 3 museos de clase mundial.",
    duracion_hrs: 8,
    precio_entrada: "$180 MXN (Las Pozas adulto)",
    dificultad: "media",
    ideal_para: ["cultura", "fotografia", "pareja"],
    horario: "09:00–18:00",
    dias_abierto: "Miércoles a Lunes — Las Pozas CIERRA los martes",
    mejor_hora: "08:30–10:00",
    temporada_ideal: "Nov–Mar",
    advertencias: "No manejar hacia Xilitla después de las 18:00 — carreteras sin iluminación y neblina densa. Cajeros pueden quedarse sin fondos en puentes. Reservación hasta 60 días antes en temporada alta. Guía obligatorio en Las Pozas (+$30 MXN).",
    como_llegar: "90 min desde Valles · Carretera 85 sur → desvío Carr. 120 hacia Xilitla · 100% pavimentado",
    que_llevar: ["calzado suela de goma con tracción profunda (trail running)", "ropa oscura o colores tierra (musgo mancha permanentemente)", "efectivo suficiente (cajeros pueden vaciarse)", "reservación anticipada de Las Pozas", "paraguas o impermeable ligero"],
    datos_curiosos: [
      "La helada de 1962 mató miles de orquídeas de Edward James — decidió construir flores de concreto que 'nunca morirían'. De ahí nacieron Las Pozas.",
      "Edward James financió a Salvador Dalí y René Magritte, y mantuvo correspondencia con Frank Lloyd Wright — influencias visibles en la escala y fantasía de Las Pozas.",
    ],
    errores_comunes: ["Llegar martes (Las Pozas CERRADO — error muy frecuente)", "No reservar con anticipación en temporada alta"],
    lat: 21.385278,
    lng: -98.989444,
    imagen_hero: "/imagenes/xilitla-pueblo-magico/hero.jpg",
    imagen_galeria: [
      "/imagenes/xilitla-pueblo-magico/gallery-1.jpg",
      "/imagenes/xilitla-pueblo-magico/gallery-2.jpg",
    ],
    seo: {
      metaTitle: "Xilitla Huasteca Potosina 2026 | Guía de Viaje Completa",
      metaDescription: "Planifica tu visita a Xilitla, el pueblo surrealista de la Huasteca Potosina. Horarios 2026, costos de Las Pozas ($180 MXN), museos y consejos de seguridad. ¡Vive la magia!",
      keywords: ["xilitla san luis potosí 2026", "jardín escultórico edward james boletos", "museo leonora carrington xilitla precios", "cómo llegar a xilitla desde ciudad valles", "pueblos mágicos huasteca potosina"],
      faqPrincipales: [
        { pregunta: "¿Cuánto tiempo se necesita para recorrer Xilitla?", respuesta: "Mínimo 2 días: el primero para Las Pozas completo y la Cascada Los Comales, el segundo para los museos del centro y el Huapango dominical en la plaza." },
        { pregunta: "¿Es seguro viajar a Xilitla en 2026?", respuesta: "Sí, es seguro siempre que se transite de día. El principal riesgo no es la violencia sino las condiciones de las carreteras de sierra: neblina densa, curvas cerradas y falta de iluminación nocturna." },
        { pregunta: "¿Cuánto cuesta la entrada a Las Pozas de Xilitla en 2026?", respuesta: "Adultos: $180 MXN. Niños 6–12 años y adultos mayores con INAPAM: $120 MXN. Menores de 6 años: gratis. Guía obligatorio adicional: $30 MXN en español." },
      ],
    },
  },
];
