export const DESTINOS_DB = [
  {
    id: "xilitla_pozas", slug: "las-pozas-jardin-surrealista",
    nombre: "Las Pozas (Jardín Surrealista)", zona: "Xilitla", tipo: "Arte & Naturaleza", emoji: "🏛️",
    descripcion: "El icónico jardín surrealista de Edward James: esculturas de concreto entre cascadas y selva tropical.",
    duracion_hrs: 4, precio_entrada: "$180 MXN", dificultad: "media",
    ideal_para: ["fotografia", "pareja", "solo", "cultura"],
    horario: "09:00–18:00", dias_abierto: "Miércoles a Lunes (cerrado martes)",
    mejor_hora: "09:00–11:00", temporada_ideal: "Nov–Mar",
    advertencias: "Comprar ticket digital antes. Cerrado martes.",
    como_llegar: "1h 45min desde Valles · Taxi $1,200 · Bus $110",
    que_llevar: ["calzado antiderrapante", "repelente biodegradable"],
    datos_curiosos: ["Fue plantación de orquídeas", "Edward James nunca vivió en las estructuras"],
    errores_comunes: ["Llegar sin reservación", "Calzado liso"],
    lat: 21.3972, lng: -98.9939,
  },
  {
    id: "cascada_tamul", slug: "cascada-de-tamul",
    nombre: "Cascada de Tamul", zona: "Aquismón", tipo: "Aventura", emoji: "🌈",
    descripcion: "La cascada más alta de SLP (105m), accesible remando por el río Tampaón. Espectacular caída turquesa.",
    duracion_hrs: 5, precio_entrada: "$220 MXN + $300 panga p/p", dificultad: "alta",
    ideal_para: ["aventura", "fotografia", "amigos"],
    horario: "08:00–17:00", dias_abierto: "Lun-Dom",
    mejor_hora: "08:00", temporada_ideal: "Ene–Abr",
    advertencias: "Lancheros dejan de salir a las 2 PM. SOLO EFECTIVO.",
    como_llegar: "45 min desde Valles → Tanchachín + lancha",
    que_llevar: ["chaleco salvavidas", "aqua shoes", "agua 2L"],
    datos_curiosos: ["105m de caída", "En octubre: agua turquesa + follaje naranja"],
    errores_comunes: ["Llegar tarde", "No llevar efectivo"],
    lat: 21.8014, lng: -99.1794,
  },
  {
    id: "sotano_golondrinas", slug: "sotano-de-las-golondrinas",
    nombre: "Sótano de las Golondrinas", zona: "Aquismón", tipo: "Extrema", emoji: "🐦",
    descripcion: "Abismo kárstico de 333m. Santuario de vencejos con vuelo espiral al amanecer.",
    duracion_hrs: 3, precio_entrada: "$100 MXN", dificultad: "media",
    ideal_para: ["fotografia", "naturaleza", "solo"],
    horario: "06:00–18:00", dias_abierto: "Lunes a Domingo",
    mejor_hora: "05:45 AM", temporada_ideal: "Nov–Mar",
    advertencias: "568 escalones para bajar; subida AGOTADORA.",
    como_llegar: "1h 15min desde Valles por sierra",
    que_llevar: ["chamarra", "lámpara", "calzado tenis"],
    datos_curiosos: ["Las aves son VENCEJOS, no golondrinas", "Fondo = 3 campos de fútbol"],
    errores_comunes: ["Llegar a las 9 AM cuando aves ya salieron"],
    lat: 21.6001, lng: -99.0989,
  },
  {
    id: "cascada_micos", slug: "cascadas-de-micos",
    nombre: "Cascadas de Micos", zona: "Ciudad Valles", tipo: "Aventura", emoji: "💦",
    descripcion: "Serie de 7 cascadas con circuito de saltos, tirolesa, kayak y skybike.",
    duracion_hrs: 4, precio_entrada: "$100 MXN", dificultad: "media",
    ideal_para: ["amigos", "aventura"],
    horario: "08:00–18:00", dias_abierto: "Lunes a Domingo",
    mejor_hora: "09:00 AM", temporada_ideal: "Todo el año",
    advertencias: "Chaleco y casco OBLIGATORIO.",
    como_llegar: "20 min desde Valles · Combis $35 MXN c/30 min",
    que_llevar: ["aqua shoes", "ropa dry-fit"],
    datos_curiosos: ["El río más versátil de la zona"],
    errores_comunes: ["No ajustar bien el chaleco"],
    lat: 21.9958, lng: -99.1678,
  },
  {
    id: "cascada_puente_dios", slug: "puente-de-dios-tamasopo",
    nombre: "Puente de Dios (Tamasopo)", zona: "Tamasopo", tipo: "Naturaleza", emoji: "🌀",
    descripcion: "Poza azul cobalto bajo puente natural. La luz entra a la cueva entre 11:00–13:00.",
    duracion_hrs: 3.5, precio_entrada: "$150 MXN", dificultad: "media",
    ideal_para: ["pareja", "fotografia"],
    horario: "08:00–17:00", dias_abierto: "Lunes a Domingo",
    mejor_hora: "11:00–13:00", temporada_ideal: "Ene–May",
    advertencias: "Corrientes fuertes; seguir cuerda de seguridad.",
    como_llegar: "1h desde Valles por autopista a SLP",
    que_llevar: ["aqua shoes OBLIGATORIOS", "chaleco"],
    datos_curiosos: ["Efecto de luz en la cueva único en México"],
    errores_comunes: ["No usar aqua shoes (piedras MUY resbalosas)"],
    lat: 21.9214, lng: -99.4217,
  },
  {
    id: "tamtoc", slug: "zona-arqueologica-tamtoc",
    nombre: "Zona Arqueológica Tamtoc", zona: "Tamuín", tipo: "Arqueología", emoji: "🗿",
    descripcion: "El asentamiento prehispánico más importante de la cultura Huasteca.",
    duracion_hrs: 3, precio_entrada: "$95 MXN", dificultad: "baja",
    ideal_para: ["historia", "cultura", "familia"],
    horario: "09:00–17:00", dias_abierto: "Martes a Domingo",
    mejor_hora: "09:00 AM", temporada_ideal: "Dic–Feb",
    advertencias: "POCA sombra. Puede superar 45°C en mayo.",
    como_llegar: "45 min desde Valles",
    que_llevar: ["sombrero", "agua abundante", "protector solar"],
    datos_curiosos: ["Monumento 32 pesa 30 toneladas"],
    errores_comunes: ["No llevar agua", "Ir sin guía"],
    lat: 22.2131, lng: -98.8158,
  },
  {
    id: "cascada_tamasopo", slug: "cascadas-de-tamasopo",
    nombre: "Cascadas de Tamasopo", zona: "Tamasopo", tipo: "Naturaleza", emoji: "🏊",
    descripcion: "Paraíso de agua azul turquesa con pozas para nadar, ideal para familias.",
    duracion_hrs: 4, precio_entrada: "$60 MXN", dificultad: "baja",
    ideal_para: ["familia", "relajacion", "fotografia"],
    horario: "08:00–17:00", dias_abierto: "Lunes a Domingo",
    mejor_hora: "10:00–14:00", temporada_ideal: "Nov–May",
    advertencias: "SOLO bloqueador biodegradable.",
    como_llegar: "45 min desde Valles por autopista",
    que_llevar: ["traje de baño", "bloqueador biodegradable"],
    datos_curiosos: ["Las pozas cambian de color según la estación"],
    errores_comunes: ["Usar bloqueador químico"],
    lat: 21.92, lng: -99.39,
  },
  {
    id: "balneario_taninul", slug: "balneario-taninul",
    nombre: "Balneario Taninul", zona: "Ciudad Valles", tipo: "Naturaleza", emoji: "♨️",
    descripcion: "Aguas termales sulfurosas (36°C constante) y lodo terapéutico.",
    duracion_hrs: 4, precio_entrada: "$150 MXN", dificultad: "baja",
    ideal_para: ["familia", "pareja", "relajacion"],
    horario: "07:00–20:00", dias_abierto: "Lunes a Domingo",
    mejor_hora: "08:00 o 18:00", temporada_ideal: "Dic–Ene",
    advertencias: "NO llevar joyería de plata (azufre la oscurece).",
    como_llegar: "15 min desde Valles",
    que_llevar: ["traje de baño", "sandalias", "toalla"],
    datos_curiosos: ["Agua mantiene 36°C constante todo el año"],
    errores_comunes: ["Llevar joyería de plata"],
    lat: 21.9452, lng: -98.8895,
  },
];

export type Destino = typeof DESTINOS_DB[0];
